const TRANSACTION_FEE = 1;
const INITIAL_BALANCE = 100;
const INITIAL_USERS = 10;
const TRANSACTION_THRESHOLD = 5;

module.exports = {
  TRANSACTION_FEE,
  INITIAL_BALANCE,
  INITIAL_USERS,
  TRANSACTION_THRESHOLD,
};
